### ISSUE TITLE
False EC alerts and sudden Kerbal death with high time warp

### ISSUE THREAD

**Issue by npyoung** [ShotgunNinja/Kerbalism#42] opened 2016-10-08 10:59 UTC
While in time warp level 5 or 6 I get "EC depleted" alerts for my LKO and Mun surface stations, then have about 5 seconds to switch to them before I get fatality messages. When I switch, it invariably turns out that I have lots of EC, sometimes a full supply, so I get the "relax" messages.

I suspect it may be the resource routing problem from #13. If I lock command pod batteries this problem disappears. I haven't tested if I need to lock just any battery, or if the battery's position relative to root or to inhabited parts matters.

v1.1.4, KSP 1.1.3 (x64)

**Comment by thepsion5** [comment] 2016-10-08 18:49
I've seen a similar issue using v1.1.4, KSP version 1.1.3 (64 bit). Occasionally, during high time warp, I get emergency messages about depleted batteries and O2. When I switch to the craft in question EC seems to start regenerating immediately (I haven't had this issue on any craft with an RTG but I've only seen it 3-4 times).

O2 is the bigger problem though - the resource display and save file list the values as NaN (same with EC and CO2 levels listed in the save file). I can manually alter the values in the save file but they immediately go back to NaN upon loading the game. I can include my current save file if helpful, but so far I can't reliably reproduce it so I don't know if a career save with a dozen other mods is helpful.

**Comment by npyoung** [comment] 2016-10-09 02:54
Update: locking batteries doesn't fix it, just makes the issue somewhat less frequent. Getting close to unplayable here. I have to leave my game running for half an hour to hit transfer windows.

**Comment by npyoung** [comment] 2016-10-09 06:06
Also noticed that when looking at the life support GUI while this happens, battery shows as "perpetual" while climate is a full line of red bars.

**Comment by ShotgunNinja** [comment] 2016-10-24 05:07
I believe to have found the cause of this, and fixed it in next version.

Please confirm that this happened in the following circumstances:
- vessel EC production was mostly from solar panels
- vessel had a big EC consumer, like a Lab or a Greenhouse at full lighting
- the savegame had more than one vessel around

**Comment by npyoung** [comment] 2016-10-24 05:22
EC producers are all panels, both affected vessels have labs (but so does one non-affected), and there are multiple vessels in the save.

Hope the fix works! Will it be in a separate little patch or part of the 1.2-compatible release?

**Comment by ShotgunNinja** [comment] 2016-10-24 05:59
Thanks for the info. Fix will be in next release, that will be for KSP 1.2
Unfortunately I'm in the middle of a huge refactor and can't release a stand-alone hotfix for this.

**Comment by ShotgunNinja** [comment] 2016-12-06 18:36
this is fixed in the new pre release

**Closed by ShotgunNinja** 2016-12-06 18:36 UTC
Labels: bug
